### ISSUE TITLE
[Lutron] Could not connect to discovered hub:

### ISSUE THREAD

**Issue by sebastiangoldstein** [thenewwazoo/homebridge-lutron-caseta-leap#115]
**Describe The Bug:**
[Lutron] Could not connect to discovered hub:

**To Reproduce:**
running hombridge 

**Expected behavior:**
When I go to plug in settings there is a spinning gear and I can't access the settings 

**Logs:**

[24/07/2023, 09:31:51] [Lutron] Could not connect to discovered hub: Error: could not get bridge serial number from Lutron-XXXXXXXXXXXXlocal: TypeError: Cannot read properties of null (reading 'groups')
    at BridgeFinder.getBridgeID (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:128:19)
    at BridgeFinder.handleDiscovery (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:68:37)
    at MDNSServiceDiscovery.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:43:18)
    at Event.emit (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/atvik/src/sync.ts:65:29)
    at MDNSServiceDiscovery.BasicServiceDiscovery.updateService (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-discovery/src/discovery/basic-service-discovery.ts:67:24)
    at MDNSServiceDiscovery.refreshService (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-mdns/src/discovery/mdns-discovery.ts:346:8)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-mdns/src/discovery/mdns-discovery.ts:206:27)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

<img width="823" alt="Screenshot 2023-07-24 at 9 45 54 AM" src="https://github.com/thenewwazoo/homebridge-lutron-caseta-leap/assets/65564693/69856d37-9637-4b60-9459-7b511593482d">

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
In the line
```
[24/07/2023, 09:31:51] [Lutron] Could not connect to discovered hub: Error: could not get bridge serial number from Lutron-XXXXXXXXXXXXlocal: TypeError: Cannot read properties of null (reading 'groups')
```
it looks like you've X'd out the serial number. Unfortunately, I need that to diagnose the problem. It's not sensitive information, so you can include it here.

**Comment by thenewwazoo** [comment]
Going to close this up. Please reopen if you can provide that serial number (which I need to figure out why that particular line of code that extracts the serial number is broken)
