### ISSUE TITLE
SSL error when trying to associate a bridge

### ISSUE THREAD

**Issue by giladno** [thenewwazoo/homebridge-lutron-caseta-leap#117]
**Describe Your Problem:**
Can't associate my lutron bridge

**Logs:**

```
[15/08/2023, 00:03:38] [Homebridge UI] [homebridge-lutron-caseta-leap] Got request to associate with XXXXXX at 10.0.0.220
[15/08/2023, 00:03:38] [Homebridge UI] [homebridge-lutron-caseta-leap] failed to associate XXXXXX 10.0.0.220 [Error: C0FAF176:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 42
] {
  library: 'SSL routines',
  reason: 'sslv3 alert bad certificate',
  code: 'ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE'
}
[15/08/2023, 00:03:38] [Homebridge UI] [homebridge-lutron-caseta-leap] Error: Initial associate failed!
    at PluginUiServer.doAssociate (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/homebridge-ui/server.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginUiServer.processRequest (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
```

**Plugin Config:**

```json
{
    "platform": "LutronCasetaLeap",
    "name": "LutronCasetaLeap"
}
```

**Environment:**

* **Plugin Version**: v2.4.3
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.16.0
* **Operating System**: Raspbian

**Comment by thenewwazoo** [comment]
This is a fun one. Can you enable debug logging and try again? I wonder if Lutron changed the SSL media in the bridge in a recent update or something.

**Comment by giladno** [comment]
@thenewwazoo no additional logs even in debug:

```
[17/08/2023, 00:17:25] [Homebridge UI] [homebridge-lutron-caseta-leap] Got request to associate with XXXXXX at 10.0.0.220
[17/08/2023, 00:17:25] [Homebridge UI] [homebridge-lutron-caseta-leap] failed to associate XXXXXX 10.0.0.220 [Error: C09AF076:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 42
] {
  library: 'SSL routines',
  reason: 'sslv3 alert bad certificate',
  code: 'ERR_SSL_SSLV3_ALERT_BAD_CERTIFICATE'
}
[17/08/2023, 00:17:25] [Homebridge UI] [homebridge-lutron-caseta-leap] Error: Initial associate failed!
    at PluginUiServer.doAssociate (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/homebridge-ui/server.js:64:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PluginUiServer.processRequest (/var/lib/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/@homebridge/plugin-ui-utils/dist/server.js:75:30)
    ```

I also receive the same error when trying to use `lutron-leap-js` module in a test project (during pairing).


Using openssl:

```
openssl s_client -connect 10.0.0.220:8083
```

```
CONNECTED(00000003)
depth=1 C = US, ST = Pennsylvania, O = "Lutron Electronics Co., Inc.", L = Coopersburg, CN = Connect Local Access Protocol Cert Authority
verify error:num=20:unable to get local issuer certificate
verify return:0
140704327123776:error:14020412:SSL routines:CONNECT_CR_SESSION_TICKET:sslv3 alert bad certificate:/AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/libressl/libressl-3.3/ssl/ssl_pkt.c:1008:SSL alert number 42
---
Certificate chain
 0 s:/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Smart Bridge
   i:/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Local Access Protocol Cert Authority
 1 s:/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Local Access Protocol Cert Authority
   i:/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Residential Local Access Protocol Certificate Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDQzCCAiugAwIBAgIBAjANBgkqhkiG9w0BAQ0FADCBmDELMAkGA1UEBhMCVVMx
FTATBgNVBAgTDFBlbm5zeWx2YW5pYTElMCMGA1UEChMcTHV0cm9uIEVsZWN0cm9u
aWNzIENvLiwgSW5jLjEUMBIGA1UEBxMLQ29vcGVyc2J1cmcxNTAzBgNVBAMTLENv
bm5lY3QgTG9jYWwgQWNjZXNzIFByb3RvY29sIENlcnQgQXV0aG9yaXR5MB4XDTE2
MDQwMTAwMDAwMFoXDTM2MDQwMTAwMDAwMFowgYAxCzAJBgNVBAYTAlVTMRUwEwYD
VQQIEwxQZW5uc3lsdmFuaWExJTAjBgNVBAoTHEx1dHJvbiBFbGVjdHJvbmljcyBD
by4sIEluYy4xFDASBgNVBAcTC0Nvb3BlcnNidXJnMR0wGwYDVQQDExRDb25uZWN0
IFNtYXJ0IEJyaWRnZTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABPG1YyvOwAfT
y6G53V7XnSWemjTtt4jGoCI455c1XzY3l1h814jVRAqg3VBtAIW4ItDZmwpzjflK
OF3K6T9yaTyjeTB3MAkGA1UdEwQCMAAwHQYDVR0OBBYEFDcr2pz9c0/bJUTK8I4T
/LlVnUYkMB8GA1UdIwQYMBaAFFv0LZUsG5ktIV4TqHLXSd+9o5TdMAsGA1UdDwQE
AwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDQYJKoZIhvcNAQEN
BQADggEBAFEwXMVey1rF1I4up93mL+e+iEL2PLabMNcnMsr8bJBSvbKBPDVz+6Vx
z8E98gloaiWGyPzwOeKmx5Tus+3hZU5voC2U75w/vjgx6DBGFDDFarKKXBRrchu5
ClBf8TYmpMw1Kk3dIEb9HmQuZe9Q6A5eq4A8dH5qAm7iFzytj8KH81ZZaO6VgmZM
4fjWPXY4U7uOFDkg3OMYt8xldqYu7COLAajiZ5bkOvW1Jmza6nQ63qUy8OHQUj5F
F6+pc0gWD5kraU+MTJJOtHA//P6Eovs45eKCk/HlKml/3KTcCYD7/gg2JAa9PC3q
rOZo7JQOMAE2HfhxYWSJXAzP8ITv33c=
-----END CERTIFICATE-----
subject=/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Smart Bridge
issuer=/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Local Access Protocol Cert Authority
---
Acceptable client certificate CA names
/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Local Access Protocol Cert Authority
/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Lutron Integrator Program Certificate Authority
/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Lutron Residential GUI Certificate Authority
Server Temp Key: ECDH, X25519, 253 bits
---
SSL handshake has read 3131 bytes and written 105 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-ECDSA-AES256-GCM-SHA384
Server public key is 256 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-ECDSA-AES256-GCM-SHA384
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: DC1DDE450882BACD4D6768FFB97D0135B07938F86B48B9B27671858A3A39BE3DDDDA0F2F38BDEE008C3438144B1B3C28
    Start Time: 1692220959
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
```

**Comment by thenewwazoo** [comment]
So I (finally) have a few minutes to look at this, and the subject of the root cert in the lutron-leap library is
```
Subject: C=US, ST=Pennsylvania, O=Lutron Electronics Co., Inc., L=Coopersburg, CN=Caseta Local Access Protocol Cert Authority
```

which is subtly different from the one in your output, which is
```
 1 s:/C=US/ST=Pennsylvania/O=Lutron Electronics Co., Inc./L=Coopersburg/CN=Connect Local Access Protocol Cert Authority
```

I genuinely have no idea why that is different, unless Lutron changed their root CA for their device signing, which would be... well, pretty weird. Surprising, anyway.

**Comment by thenewwazoo** [comment]
I also don't see any updated cert in the [pylutron-caseta](https://github.com/gurumitts/pylutron-caseta/blob/dev/pylutron_caseta/assets.py) project.

**Comment by thenewwazoo** [comment]
Is there anything special about your Smart Bridge (Pro?)

**Comment by thenewwazoo** [comment]
Since this has gotten old and I don't have any more ideas, I'm going to close this up. Please re-open if you spot anything that could be causing this, or any ways that your setup is unusual that might help with future diagnosis.
