### ISSUE TITLE
Could not connect to discovered hub

### ISSUE THREAD

**Issue by robhester** [thenewwazoo/homebridge-lutron-caseta-leap#12]
**Describe Your Problem:**
I assume this is probably n00b error, but any chance this error has popped up for others?

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

```
 Could not connect to discovered hub: Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:65:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:63:3)
    at configSecureContext (node:internal/tls/secure-context:152:5)
    at createSecureContext (node:_tls_common:116:3)
    at new LeapClient (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:51:44)
    at BridgeFinder.handleDiscovery (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:201:28) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```

**Plugin Config:**

```json

{
            "name": "Lutron",
            "secrets": [
                {
                    "bridgeid": "01683A68",
                    "ca": "REDACTED",
                    "key": "REDACTED",
                    "cert": "REDACTED"
                }
            ],
            "platform": "LutronCasetaLeap"
        }

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.1.1
* **Homebridge Version**: 1.4
* **Node.js Version**: v16.13.1
* **NPM Version**: v8.3.0
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by robhester** [comment]
Oh boy.  Definitely a n00b error.  I thought I had to trim 'begin certificate from each.  a straight copy/paste worked for me.  

"ca": "-----BEGIN CERTIFICATE-----\nMII...",
                "key": "-----BEGIN PRIVATE KEY-----\nMII...",
                "cert": "-----BEGIN CERTIFICATE-----\nMII..."
