### ISSUE TITLE
Can't seem to get the plugin to detect my lutron hub

### ISSUE THREAD

**Issue by hmangnx** [thenewwazoo/homebridge-lutron-caseta-leap#158]
Running the latest version of the plugin, I cannot setup the plugin because it doesn't detect the hub. Is there anyway to point the ip directly to the hub? Or some other way to get around this?

**Comment by Auirsblade** [comment]
Same issue here. I have a completely fresh homebridge install, and both the homebridge and lutron hub are correctly detected by homekit, but homebridge can't reach the lutron hub.

**Comment by thenewwazoo** [comment]
Are you using docker?

**Comment by Auirsblade** [comment]
Yep, so I had to jump though some hoops to get Homebridge itself communicating on the right interface, and advertising properly over mDNS. For what it's worth, overnight I got some logs where it seemed like it found the bridge, or at least the IP+BridgeID, but the plugin setup screen still stalls. 

`2024-08-30T07:40:55.397Z leap:protocol:discovery got useful ipaddr 10.0.0.164
2024-08-30T07:40:55.397Z leap:protocol:discovery extracted bridge ID: 0512CD4B
[8/30/2024, 2:40:55 AM] [LutronCasetaLeap] no credentials from bridge ID 0512CD4B
2024-08-30T09:11:23.216Z leap:protocol:discovery checking HostAndPort { host: '10.0.0.164', port: 22 }
2024-08-30T09:11:23.218Z leap:protocol:discovery was not ipv6: Error [AddressError]: Incorrect number of groups found
    at new AddressError (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/ip-address/lib/address-error.ts:5:5)
    at Address6.parse (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/ip-address/lib/ipv6.ts:713:13)
    at new Address6 (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/ip-address/lib/ipv6.ts:153:31)
    at BridgeFinder.extractIp (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:95:30)
    at BridgeFinder.handleDiscovery (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:60:29)
    at MDNSServiceDiscovery.<anonymous> (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/BridgeFinder.ts:43:18)
    at Event.emit (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/atvik/src/sync.ts:65:29)
    at MDNSServiceDiscovery.BasicServiceDiscovery.updateService (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-discovery/src/discovery/basic-service-discovery.ts:67:24)
    at MDNSServiceDiscovery.refreshService (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-mdns/src/discovery/mdns-discovery.ts:346:8)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-lutron-caseta-leap/node_modules/tinkerhub-mdns/src/discovery/mdns-discovery.ts:206:27) {
  parseMessage: undefined
}`

These logs started after the scheduled backup, and then have popped up every ~hour and a half since.

**Comment by Auirsblade** [comment]
Oh additionally, to get the plugin to run at all (before it wasn't initializing or logging) I had to add the secrets section to the json config with some null values, and that got it at least running and logging: 
`{
    "platform": "LutronCasetaLeap",
    "name": "LutronCasetaLeap",
    "secrets": [
        {
            "bridgeid": "",
            "ca": "",
            "key": "",
            "cert": ""
        }
    ]
}`
