### ISSUE TITLE
Failed setting up Pico remote

### ISSUE THREAD

**Issue by wikweflunk** [thenewwazoo/homebridge-lutron-caseta-leap#16]
**Describe The Bug:**
 homebridge-lutron-caseta-leap v2.2.0 plugin installed. , Hombridge updated today.
Hombridge finds Lutron Bridge and Picos but can not configure them. 

Removed tag# from logs, not sure if they are sensitive.

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
1/27/2022, 11:52:32] [Lutron] Failed setting up Pico remote: Error: request with tagxxxxxxxxxxxftimed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:106:27)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[1/27/2022, 11:52:32] [Lutron] Failed to get button group(s) belonging to Living Room Alarm Mica Error: request with tagadxxxxxxxxxxxxxxxxxxtimed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:106:27)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[1/27/2022, 11:52:32] [Lutron] Failed setting up Pico remote: Error: request with tagadxxxxxxxxxxxtimed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:106:27)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-lutron-caseta-leap v2.2.0
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
Curious, I don't know what could cause this. This means that Homebridge was able to talk to the bridge, but the bridge took too long (> 3 seconds) to respond. Is the network reliable, or do you have anything else talking to the bridge?

**Comment by wikweflunk** [comment]
Network is reliable and the bridge only communicates with homekit. Any homekit to Caseta commands respond almost instantaneous.

**Comment by wikweflunk** [comment]
Installed v2.2.1. 
Not sure if this means anything. I disabled insecure mode and the picos seemed to  "set up". When I switched back to insecure, the timeout issue returned.

[1/28/2022, 07:59:58] [Lutron] Finished setting up Pico remote Living Room Floor Lamp Remote 1
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Living Room Bottom Stairs
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Living Room Top Stairs
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Kitchen Kitchen Preset
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Table
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Guest Bedroom Pico
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Basement Stairs Pico 1
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Basement Stairs Top
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Master Bedroom Pico
[1/28/2022, 07:59:59] [Lutron] Finished setting up Pico remote Living Room Alarm Mica
[1/28/2022, 08:00:20] [Homebridge UI] Homebridge must be running in insecure mode to control accessories

**Comment by thenewwazoo** [comment]
Weird. I don’t honestly don’t understand what that toggle does, but it’s enabled by default and I’ve never tested … well, anything at all, really, without it.

**Comment by rcoletti116** [comment]
Add this one to the weird behavior I’ve seen. This started happening to me today. I noticed at first that my Picos stopped working, then restarted my homebridge and got these timeouts in the logs. Can’t seem to get it working now. I restarted the lutron hub and homebridge server. Both are hardwired on the network. 
The plugin still discovers all of my connected devices, but times out at set up so the devices won’t work. Does the timeout here just need to be a bit longer?

oh, and turning off insecure mode doesn’t change anything.

**Comment by rcoletti116** [comment]
I manually changed the timeout in BridgeManager from 5 to 7 seconds to solve this for me. That does seem like a long time to wait for a response though. Maybe this could be configurable in the future.

**Comment by thenewwazoo** [comment]
You’re running it on an RPi, right? Which model? I have a growing suspicion that a lightly loaded Pi slows nodejs down a bunch.

**Comment by rcoletti116** [comment]
Pi 3B+

**Comment by thenewwazoo** [comment]
it feels like papering over the problem to just increase the timeouts, but it sounds like that's what's actually warranted, eh?

**Comment by rcoletti116** [comment]
I agree with you. I'm fine to leave mine as a custom edit. I wouldn't change it for everyone unless it was a configuration option.

**Comment by thenewwazoo** [comment]
I've increased the timeouts to values long enough that Homebridge will actually give up on the characteristic read/write action. I should rein them in at some point in the future, but I'm basically as permissive as I can be. Hopefully this helps prevent problems when you get unlucky w/ slower hardware.
