### ISSUE TITLE
Loses connection after a few days 

### ISSUE THREAD

**Issue by thenewwazoo** [thenewwazoo/homebridge-lutron-caseta-leap#2]
After a few days, the plugin ceases to be responsive and can be restored by restarting Homebridge.

Relevant log snippet?

```
[02/02/2021, 14:55:11] [LutronCasetaLeap] blinds Living Room Center were set to adjusted value 0
[02/02/2021, 14:55:11] [LutronCasetaLeap] blinds Office Right Window were set to adjusted value 0
[02/02/2021, 14:55:11] [LutronCasetaLeap] blinds Living Room Right were set to adjusted value 0
[02/02/2021, 14:55:11] [LutronCasetaLeap] blinds Office Left Window were set to adjusted value 0
[02/02/2021, 14:55:11] [LutronCasetaLeap] blinds Living Room Left were set to adjusted value 0
(node:3457) UnhandledPromiseRejectionWarning: Error: request timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:110:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3457) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3457) UnhandledPromiseRejectionWarning: Error: request timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:110:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3457) UnhandledPromiseRejectionWarning: Error: request timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:110:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3457) UnhandledPromiseRejectionWarning: Error: request timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:110:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:3457) UnhandledPromiseRejectionWarning: Error: request timed out
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:110:27)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:3457) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
```

Clearly I need to add some catch blocks :)

**Comment by thenewwazoo** [comment]
I think is happening because `SmartBridge.setBlindsTilt` doesn't await the call to `this.client.request`.

**Comment by thenewwazoo** [comment]
Added the tag to timeout err output in lutron-leap 1.1.0 and bumped ver to try and track. I've got it running at home w/ debug logging enabled.

**Comment by thenewwazoo** [comment]
This hasn't popped up in a while since I fixed the stale connection bug, so I'm going to close it up and reopen if it recurs.

**Comment by JonDror** [comment]
@thenewwazoo 
Happening again with v2.1.0-beta.6 while working with Pico remotes. After a few days, the remotes are unresponsive.

Last few DEBUG lines before socket is closed (some data redacted)
```
2022-01-11T19:38:04.078Z leap:responseparser parsing line {"CommuniqueType":"ReadResponse","Header":{"MessageBodyType":"OnePingResponse","StatusCode":"200 OK","Url":"/server/1/status/ping","ClientTag":"xxxxxx-xxxxxx-xxxxxx"},"Body":{"PingResponse":{"LEAPVersion":1.114}}}
2022-01-11T19:38:04.078Z leap:message:bodytype parsing body type OnePingResponse with data: { PingResponse: { LEAPVersion: 1.114 } }
2022-01-11T19:38:04.078Z leap:protocol got response to tag xxxxxx-xxxxxx-xxxxxx
2022-01-11T19:38:04.078Z leap:protocol tag xxxxxx-xxxxxx-xxxxxx  recognized as in-flight
2022-01-11T19:39:04.076Z leap:protocol added promise to inFlightRequests with tag key xxxxxx-xxxxxx-xxxxxx
2022-01-11T19:39:04.076Z leap:protocol request handler about to write: {"CommuniqueType":"ReadRequest","Header":{"ClientTag":"xxxxxx-xxxxxx-xxxxxx","Url":"/server/1/status/ping"}}
2022-01-11T19:39:04.076Z leap:protocol sent request tag xxxxxx-xxxxxx-xxxxxx  successfully
2022-01-11T19:39:05.076Z leap:bridge Ping timeout
2022-01-11T19:39:05.080Z leap:protocol client socket has closed.
```

Last Plug-ing logs:
```
[1/11/2022, 1:32:38 PM] [LutronCasetaLeap] button  /button/111  was released
[1/11/2022, 1:32:52 PM] [LutronCasetaLeap] handling event from button  /button/113
[1/11/2022, 1:32:52 PM] [LutronCasetaLeap] button  /button/113  was  Press
[1/11/2022, 1:32:52 PM] [LutronCasetaLeap] handling event from button  /button/113
[1/11/2022, 1:32:52 PM] [LutronCasetaLeap] button  /button/113  was released
```

**Comment by thenewwazoo** [comment]
Hm, I think you've found a separate issue. It looks like it got a ping response at 19:38:04 but the ping timeout expired at 19:39:05, one minute later. I'm not quite sure why that would happen. If you still have more logs, I wouldn't mind seeing the prior few minutes to include another ping. Would you mind opening another issue to track it?

**Comment by thenewwazoo** [comment]
Hey @JonDror, has this recurred? I haven't been able to reproduce (or, rather, it hasn't happened to me). I'd like to get some logs that include everything between 3 or so ping cycles.

**Comment by JonDror** [comment]
@thenewwazoo Yes! But the debug was off 🤦‍♂️
I should have more logs from the first occurrence.. just haven’t had the time to gather them for the new issue I want to open. Hoping to get to it this weekend

**Comment by JonDror** [comment]
Just saw the new release! I’ll open a new issue if this happens again. Thank you so much this is amazing!
