### ISSUE TITLE
Cannot Connect to the bridge

### ISSUE THREAD

**Issue by colmanllflee** [thenewwazoo/homebridge-lutron-caseta-leap#25]
**Describe Your Problem:**

Cannot connect to Lutron Bridge
**Logs:**
2022-02-17, 2:15:27 AMLutron Caseta Leap BridgeConfiguration change
2022-02-17, 2:15:27 AMlutroncasetaleapbridge stopping
2022-02-17, 2:15:33 AMLutron Caseta Leap Bridge starting
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeLoaded plugin 'homebridge-lutron-caseta-leap'
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeLoading 1 platforms...
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap starting up...
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeLutronCasetaLeapLutronCasetaLeap plugin finished early initialization
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeLutronCasetaLeapFinished launching; starting up automatic discovery
2022-02-17, 2:15:43 AMLutron Caseta Leap BridgeBridge is running on port 51886.
2022-02-17, 2:15:44 AMLutron Caseta Leap BridgeLutronCasetaLeapERRORCould not connect to discovered hub: Error: error:0909006C:PEM routines:get_name:no start line
    at node:internal/tls/secure-context:65:13
    at Array.forEach (<anonymous>)
    at setCerts (node:internal/tls/secure-context:63:3)
    at configSecureContext (node:internal/tls/secure-context:152:5)
    at createSecureContext (node:_tls_common:117:3)
    at new LeapClient (/var/lib/hoobs/lutroncasetaleapbridge/node_modules/lutron-leap/src/LeapClient.ts:51:44)
    at BridgeFinder.handleDiscovery (/var/lib/hoobs/lutroncasetaleapbridge/node_modules/lutron-leap/src/BridgeFinder.ts:199:28) {
  library: 'PEM routines',
  function: 'get_name',
  reason: 'no start line',
  code: 'ERR_OSSL_PEM_NO_START_LINE'
}
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

    "platform": "LutronCasetaLeap",
    "secrets": [
        {
            "bridgeid": "02C18E0B",
            "ca": "-----BEGIN CERTIFICATE----- MIICGTC -----END CERTIFICATE-----",
            "key": "-----BEGIN PRIVATE KEY----- MIIEvgIBA -----END PRIVATE KEY-----",
            "cert": "-----BEGIN CERTIFICATE----- MIIC2zc -----END CERTIFICATE-----"
        }
    ]
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.2.3
* **Homebridge Version**:  1.4.0
* **Node.js Version**:  16.14.0
* **NPM Version**: 
* **Operating System**:

**Comment by thenewwazoo** [comment]
`code: 'ERR_OSSL_PEM_NO_START_LINE'` indicates that you weren't able to copy the files correctly. I've actually just (tonight) wrapped up a new UI that does all that for you - you just click some buttons. It'll be released in a few days. Let me know if you'd like to be an early tester :)
