### ISSUE TITLE
Beta New UI Failing

### ISSUE THREAD

**Issue by rcoletti116** [thenewwazoo/homebridge-lutron-caseta-leap#27]
**Describe The Bug:**

Using the new UI - fails to connect

**To Reproduce:**
Use new UI and attempt to connect to the bridge.

**Expected behavior:**

**Logs:**

```
Uncaught TypeError: Cannot read properties of undefined (reading 'toAssociated')
    at HomebridgePluginUi.handleConnected (index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:95:19)
    at HomebridgePluginUi._handleIncomingMessage (ui.ts:82:14)
handleConnected @ index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:95
_handleIncomingMessage @ ui.ts:82
postMessage (async)
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.onevent @ main-es2015.9d482d945810494ac85a.js:1
p.onpacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.ondecoded @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
d.add @ main-es2015.9d482d945810494ac85a.js:1
p.ondata @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
c.onPacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
n.onPacket @ main-es2015.9d482d945810494ac85a.js:1
n.onData @ main-es2015.9d482d945810494ac85a.js:1
ws.onmessage @ main-es2015.9d482d945810494ac85a.js:1
T @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
onInvokeTask @ main-es2015.9d482d945810494ac85a.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
runTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
p @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
f @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:172 connect request complete for 02725C24 10.0.0.251
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:221 CONNECTING 02725C24 timeout
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:320 toFailed 02725C24 Connection timed out
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta3:326 in FAILED clearing CONNECTING timeout 02725C24
```

**Environment:**

* **Plugin Version**: 2.3.0 Beta 3
* **Homebridge Version**: 1.4.0
* **Node.js Version**: v16.14.0
* **NPM Version**: v8.5.0
* **Operating System**: Raspbian

**Comment by thenewwazoo** [comment]
Killer, thank you so much! Can you add the browser and version?

**Comment by rcoletti116** [comment]
Chrome Version 98.0.4758.102 (Official Build) (x86_64)
Safari Version 15.2 (17612.3.6.1.6)

**Comment by thenewwazoo** [comment]
I've made some updates and released a newer beta version. I'm still not quite sure why that first error happened. LMK how it goes.

**Comment by rcoletti116** [comment]
Full console logs from latest beta, still not connecting.

```shell
listening for connected
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:130 listening for failed
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:147 listening for associated
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:150 setup done
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:156 exiting
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:78 found bridge {bridgeid: '02725C24', ipAddr: '10.0.0.251', systype: 'SmartBridge'}
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:204 new bridge 02725C24 10.0.0.251
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:85 sending connect request for 02725C24 10.0.0.251
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:230 toConnecting 02725C24
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:101 success connected to bridge 032E7E88
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:104 failed trying to get connected bridge 032E7E88 from map
handleConnected @ index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:104
_handleIncomingMessage @ ui.ts:82
postMessage (async)
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.onevent @ main-es2015.9d482d945810494ac85a.js:1
p.onpacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.ondecoded @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
d.add @ main-es2015.9d482d945810494ac85a.js:1
p.ondata @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
c.onPacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
n.onPacket @ main-es2015.9d482d945810494ac85a.js:1
n.onData @ main-es2015.9d482d945810494ac85a.js:1
ws.onmessage @ main-es2015.9d482d945810494ac85a.js:1
T @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
onInvokeTask @ main-es2015.9d482d945810494ac85a.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
runTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
p @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
f @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:105 Map(1)[[Entries]]0: {"02725C24" => Bridge}size: 1[[Prototype]]: Map
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:106 Uncaught Error: could not find connected bridge 032E7E88 in map
    at HomebridgePluginUi.handleConnected (index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:106:27)
    at HomebridgePluginUi._handleIncomingMessage (ui.ts:82:14)
handleConnected @ index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:106
_handleIncomingMessage @ ui.ts:82
postMessage (async)
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.onevent @ main-es2015.9d482d945810494ac85a.js:1
p.onpacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
p.ondecoded @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
d.add @ main-es2015.9d482d945810494ac85a.js:1
p.ondata @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
c.onPacket @ main-es2015.9d482d945810494ac85a.js:1
(anonymous) @ main-es2015.9d482d945810494ac85a.js:1
t.emit @ main-es2015.9d482d945810494ac85a.js:1
n.onPacket @ main-es2015.9d482d945810494ac85a.js:1
n.onData @ main-es2015.9d482d945810494ac85a.js:1
ws.onmessage @ main-es2015.9d482d945810494ac85a.js:1
T @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
onInvokeTask @ main-es2015.9d482d945810494ac85a.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
runTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
invokeTask @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
p @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
f @ polyfills-es2015.e8bb8be2ebc926cac2d0.js:1
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:185 connect request complete for 02725C24 10.0.0.251
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:234 CONNECTING 02725C24 timeout
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:333 toFailed 02725C24 Connection timed out
index.html?origin=http%3A%2F%2F10.0.0.75%3A8581&v=2.3.0-beta4:339 in FAILED clearing CONNECTING timeout 02725C24
```

**Comment by thenewwazoo** [comment]
Oh my god. What a stupid, stupid mistake. I'm dying laughing here.

I left my own hard-coded bridge ID from testing. Which explains why it worked for me!

**Comment by thenewwazoo** [comment]
Beta 8 is out.

**Comment by thenewwazoo** [comment]
Followed up on Discord and it sounds like all is well!
