### ISSUE TITLE
Newest release won't start

### ISSUE THREAD

**Issue by wsmeyer90277** [thenewwazoo/homebridge-lutron-caseta-leap#42]
I saw that you added 4 button remote support and was excited to update. 

Unfortunately it no longer works at all and sends homebridge into a crash reboot cycle. 

It all starts with - failed to get buttons from button group.... And then names pico remotes that used to work in the plug in. 

I'm on my iPad right now and can't seem to copy paste but let me know if you need more info.

**Comment by thenewwazoo** [comment]
Can you try restarting Homebridge? (Maybe more than once). I suspect you’re seeing #10

**Comment by wsmeyer90277** [comment]
I've restarted homebridge and the Pi several times and even cleared the accessory cache.

**Comment by thenewwazoo** [comment]
Darn. Okay, when you can, please attach debug logs. I'll need to trace what's happening.

**Comment by thenewwazoo** [comment]
Oh! Also, what does your remote look like? I wonder if my assumption that the Pico4ButtonScene functions the same as the Pico4ButtonZone (a mistake I've made once before...).

**Comment by wsmeyer90277** [comment]
Bright - Entertain - Movie - Off
And
Bright - Cooking - Dining - Off

Working on the logs now.

**Comment by wsmeyer90277** [comment]
Logs...

[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type SmartBridge supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type PlugInDimmer not recognized, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 3185a19e-b55d-40a4-bd6f-060c7c15985e Family Room Table Lamp Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 7f99d326-ee8b-4017-ab19-ca794346250b Master Bedroom All Lights already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type PlugInDimmer not recognized, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 644ade81-64b8-4dbd-8383-c53e97279b33 Master Bedroom W Table Lamp already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type PlugInDimmer not recognized, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 68223235-00d7-4820-87ee-c503f0221278 Chloe's Bedroom Ceiling Light Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallSwitch supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallSwitch supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico2Button 86728871-74ee-4590-ba72-e760387cbe79 Stairway Middle Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico2Button 14be25ce-79f0-4589-be35-e409f905abdb Stairway Lower Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallSwitch supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico2Button 77a29a90-4e68-4528-ae8d-b48205dca43d Stairway Upper Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 607b2a79-34a1-4efe-b6e0-fc8fdd6d56f4 Charlie's Bedroom Ceiling Light Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 93ebd8d5-a85a-453c-b0d1-ddb68185fe8e Kitchen Main Lights Wall Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 1b0667b8-4441-4658-a103-f8949fb0fa69 Master Bathroom Shower Pico 2 already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico2Button 4856df22-9a00-4053-ad15-d1a50cf717e3 Front Foyer Keypad already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 3e23da2b-9265-4a55-a181-b9e85603148a Dining Room Chandelier Ped Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 101e28f0-7b0b-43c1-ba39-d009ce8a421b Dining Room Chandelier Wall Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type PlugInDimmer not recognized, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 2a889e45-bc35-47f3-a1db-f77479234941 Living Room Floor Lamp Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 8d90daea-f62a-4755-97dd-1e002997f7ed Hallway Middle Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 7a0e2e41-71c2-4cf7-86ed-e67a19e34b28 Master Bathroom Tub Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 4b46ac3b-4707-4c23-b960-567a648030a7 Rooftop Deck Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WirelessAuxRepeater not recognized, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower d6ae2a85-641f-415a-ab25-4e0e87fad81a Master Bathroom Tub Pico All already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallSwitch supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower ab4c89e5-14da-48fb-b7b1-d7a2877798fd Family Room Table and Spot Wall Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallSwitch supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Device type WallDimmer supported natively, skipping setup
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 9cbe20b2-8861-411e-897d-c0b0ca3205c6 Family Room Audio Pico already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower 96691db7-f081-423f-bf4b-4f85e315b860 Master Bathroom Shower Pico 1 already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico2Button 5f6f7c1c-0750-406b-9728-e08c7018b1ae Garage Home Away already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico4ButtonScene 0a273879-afba-4b94-9869-8062680e7587 Kitchen Keypad already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico4ButtonScene a894e84f-d6bc-4df9-a20c-e8f96f123b95 Family Room Keypad already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico4ButtonScene 650d8d33-9397-4047-8b88-ef8e8bea70fa Master Bedroom W Keypad already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico4ButtonScene c00a3019-3fc1-4052-beac-3d8ff60df6d3 Master Bedroom C Keypad already set up. Skipping.
[5/7/2022, 11:37:29 AM] [LutronCasetaLeap] Accessory Pico3ButtonRaiseLower b164ef5a-520c-4a2d-9ea2-5236aa46c81c Master Bedroom C Table Lamp already set up. Skipping.
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Kitchen Main Lights Wall Pico Error: request with tag0d403e95-2893-44bd-a7cf-807a29738867timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag0d403e95-2893-44bd-a7cf-807a29738867timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bathroom Shower Pico 2 Error: request with tag1e7d9ada-f157-4fe1-83ef-91692281c52etimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag1e7d9ada-f157-4fe1-83ef-91692281c52etimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Front Foyer Keypad Error: request with tag4ed95be2-abe6-4a60-addf-3aafc60e6be1timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag4ed95be2-abe6-4a60-addf-3aafc60e6be1timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Dining Room Chandelier Ped Pico Error: request with tag3e24d8f3-5a23-4496-b6ae-b3a0835bc0e4timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag3e24d8f3-5a23-4496-b6ae-b3a0835bc0e4timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Dining Room Chandelier Wall Pico Error: request with tag6187c02d-c98f-491c-8b6a-4205b7bfe6bdtimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag6187c02d-c98f-491c-8b6a-4205b7bfe6bdtimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Living Room Floor Lamp Pico Error: request with tagb6198760-53a5-46d1-8b8f-7b14ed79649ftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagb6198760-53a5-46d1-8b8f-7b14ed79649ftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Hallway Middle Pico Error: request with tagb67abf22-7549-493c-9a3a-1623e7c775d1timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagb67abf22-7549-493c-9a3a-1623e7c775d1timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bathroom Tub Pico Error: request with tagc52a2e2d-3e22-4116-aad5-eee4488ee8batimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagc52a2e2d-3e22-4116-aad5-eee4488ee8batimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Rooftop Deck Pico Error: request with tag00e706d7-e423-4587-b6dd-de51b053cc8btimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag00e706d7-e423-4587-b6dd-de51b053cc8btimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bathroom Tub Pico All Error: request with tag617af0ba-bb16-42d8-bc3f-dbdb66236ebftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag617af0ba-bb16-42d8-bc3f-dbdb66236ebftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Family Room Table and Spot Wall Pico Error: request with tag84a7c0f7-89ec-49b3-9dc7-6a32198ed4datimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag84a7c0f7-89ec-49b3-9dc7-6a32198ed4datimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Family Room Audio Pico Error: request with tag6a33e03a-a3bb-46bc-be5f-cdb91d525f7btimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag6a33e03a-a3bb-46bc-be5f-cdb91d525f7btimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bathroom Shower Pico 1 Error: request with tag85e862c0-dbdb-4c35-aed8-1735d92bac7dtimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag85e862c0-dbdb-4c35-aed8-1735d92bac7dtimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Garage Home Away Error: request with tag6376062a-ea6c-4c79-a881-2f1de7518061timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag6376062a-ea6c-4c79-a881-2f1de7518061timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Kitchen Keypad Error: request with tagdb03c741-38e2-4055-a843-d2beded6e2ectimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagdb03c741-38e2-4055-a843-d2beded6e2ectimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Family Room Keypad Error: request with tag1db44913-0e02-45f3-9d92-238f41ea3a14timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag1db44913-0e02-45f3-9d92-238f41ea3a14timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bedroom W Keypad Error: request with tag569d363f-37c5-4d85-979f-466448de2bf5timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag569d363f-37c5-4d85-979f-466448de2bf5timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bedroom C Keypad Error: request with tagaeb23ead-d14f-45f7-b2b6-935aac459b85timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagaeb23ead-d14f-45f7-b2b6-935aac459b85timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed to get button group(s) belonging to Master Bedroom C Table Lamp Error: request with tagdb749e79-b8bc-427a-8475-b8c54140c87ftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:32 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagdb749e79-b8bc-427a-8475-b8c54140c87ftimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:34 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/19
[5/7/2022, 11:37:34 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagb5e2c645-a9ee-4a07-ab26-ce7508df804atimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:34 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/22
[5/7/2022, 11:37:34 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tagc853cc2b-4538-4a1f-81bf-70e5a68e4bc6timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:35 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/24
[5/7/2022, 11:37:35 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag60f5af4f-4a87-4c6d-9466-0b61a3ba2104timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:35 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/28
[5/7/2022, 11:37:35 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag2b3549f5-57e9-44b6-8720-a505543ebcbatimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:36 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/30
[5/7/2022, 11:37:36 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag5dd55a50-17a4-4fdc-9063-a3f30053773ctimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:36 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/31
[5/7/2022, 11:37:36 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag8adf2f70-4e66-4b71-a16d-2752e9f3cc8dtimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:37 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/32
[5/7/2022, 11:37:37 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag6e7b2768-fa80-443e-856c-560ed7dce192timed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[5/7/2022, 11:37:37 AM] [LutronCasetaLeap] Failed to get buttons from button group /buttongroup/33
[5/7/2022, 11:37:37 AM] [LutronCasetaLeap] Failed setting up Pico remote: Error: request with tag54f74855-d97a-45a1-8e4a-ece6aa2b95aatimed out
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lutron-caseta-leap/node_modules/lutron-leap/src/LeapClient.ts:114:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by thenewwazoo** [comment]
That does indeed look a lot like #10, especially since older, already-supported Picos are not working. I'm going to close this in favor of continuing there, but ask that you enable debug logging (see the README for instructions) and add it to that thread so I can keep investigating. Could you also leave a comment there with more info about your hardware setup?
